sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.3.0-rc.1
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix node
